# Generated by Django 3.0 on 2024-05-27 13:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('translations', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'db_table': 'allergy',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('translations', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('allergy_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_allergy',
                'unique_together': {('user_id', 'allergy_id')},
            },
        ),
        migrations.CreateModel(
            name='IngredientsAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.IntegerField()),
                ('allergy_id', models.IntegerField()),
            ],
            options={
                'db_table': 'IngredientsAllergy',
                'unique_together': {('ingredient_id', 'allergy_id')},
            },
        ),
    ]
