# Generated by Django 5.0.4 on 2024-05-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0002_ingredients_ingredientsallergy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userallergy',
            old_name='user_uuidv4',
            new_name='user_id',
        ),
    ]
