# Generated by Django 5.0.4 on 2024-05-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0003_rename_user_uuidv4_userallergy_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userallergy',
            unique_together={('user_id', 'allergy_id')},
        ),
    ]
