# Generated by Django 5.0.4 on 2024-05-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0004_alter_userallergy_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsallergy',
            unique_together={('ingredient_id', 'allergy_id')},
        ),
    ]
