# Generated by Django 5.0.4 on 2024-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0005_alter_ingredientsallergy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='translations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
