# Generated by Django 5.0.4 on 2024-07-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0006_ingredients_translations_alter_ingredients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergy',
            name='foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeservice.ingredients'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='PFC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Squirrels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='same_ingridient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_ingridients', to='recipeservice.ingredients'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='translations',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ingridients', models.JSONField()),
                ('translations', models.JSONField()),
                ('image', models.CharField(max_length=255)),
                ('same_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeservice.dish')),
            ],
            options={
                'db_table': 'dish',
            },
        ),
    ]
