# Generated by Django 5.0.4 on 2024-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0007_allergy_comment_allergy_foods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingridients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsallergy',
            name='allergy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsallergy',
            name='ingredient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
