# Generated by Django 5.0.4 on 2024-07-22 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0008_alter_allergy_translations_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='translations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
