# Generated by Django 5.0.7 on 2024-07-29 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0010_remove_allergy_foods_alter_ingredients_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userallergy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='IngredientsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(related_name='categories', to='recipeservice.ingredients')),
            ],
            options={
                'db_table': 'ingredients_category',
            },
        ),
    ]
