# Generated by Django 5.0.4 on 2024-07-29 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeservice', '0014_alter_ingredientscategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userallergy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
