# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from recipe_proto import allergy_pb2 as recipe__proto_dot_allergy__pb2


class AllergyControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/allergy.AllergyController/List',
                request_serializer=recipe__proto_dot_allergy__pb2.AllergyListRequest.SerializeToString,
                response_deserializer=recipe__proto_dot_allergy__pb2.AllergyListResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/allergy.AllergyController/Create',
                request_serializer=recipe__proto_dot_allergy__pb2.AllergyCreateRequest.SerializeToString,
                response_deserializer=recipe__proto_dot_allergy__pb2.AllergyCreateResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/allergy.AllergyController/Retrieve',
                request_serializer=recipe__proto_dot_allergy__pb2.AllergyRetrieveRequest.SerializeToString,
                response_deserializer=recipe__proto_dot_allergy__pb2.AllergyRetrieveResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/allergy.AllergyController/Update',
                request_serializer=recipe__proto_dot_allergy__pb2.AllergyUpdateRequest.SerializeToString,
                response_deserializer=recipe__proto_dot_allergy__pb2.AllergyUpdateResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/allergy.AllergyController/Destroy',
                request_serializer=recipe__proto_dot_allergy__pb2.AllergyDestroyRequest.SerializeToString,
                response_deserializer=recipe__proto_dot_allergy__pb2.AllergyDestroyResponse.FromString,
                )


class AllergyControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AllergyControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=recipe__proto_dot_allergy__pb2.AllergyListRequest.FromString,
                    response_serializer=recipe__proto_dot_allergy__pb2.AllergyListResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=recipe__proto_dot_allergy__pb2.AllergyCreateRequest.FromString,
                    response_serializer=recipe__proto_dot_allergy__pb2.AllergyCreateResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=recipe__proto_dot_allergy__pb2.AllergyRetrieveRequest.FromString,
                    response_serializer=recipe__proto_dot_allergy__pb2.AllergyRetrieveResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=recipe__proto_dot_allergy__pb2.AllergyUpdateRequest.FromString,
                    response_serializer=recipe__proto_dot_allergy__pb2.AllergyUpdateResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=recipe__proto_dot_allergy__pb2.AllergyDestroyRequest.FromString,
                    response_serializer=recipe__proto_dot_allergy__pb2.AllergyDestroyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'allergy.AllergyController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AllergyController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/allergy.AllergyController/List',
            recipe__proto_dot_allergy__pb2.AllergyListRequest.SerializeToString,
            recipe__proto_dot_allergy__pb2.AllergyListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/allergy.AllergyController/Create',
            recipe__proto_dot_allergy__pb2.AllergyCreateRequest.SerializeToString,
            recipe__proto_dot_allergy__pb2.AllergyCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/allergy.AllergyController/Retrieve',
            recipe__proto_dot_allergy__pb2.AllergyRetrieveRequest.SerializeToString,
            recipe__proto_dot_allergy__pb2.AllergyRetrieveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/allergy.AllergyController/Update',
            recipe__proto_dot_allergy__pb2.AllergyUpdateRequest.SerializeToString,
            recipe__proto_dot_allergy__pb2.AllergyUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/allergy.AllergyController/Destroy',
            recipe__proto_dot_allergy__pb2.AllergyDestroyRequest.SerializeToString,
            recipe__proto_dot_allergy__pb2.AllergyDestroyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
